### ISSUE TITLE
请问数据怎么统计的？

### ISSUE THREAD

**Issue by zhuweiyou** [no-Dark/Adult#1]
这个访问量排名，有什么依据？

**Comment by duminghong** [comment]
What is the basis for this ranking?

**Comment by xiaoxu97** [comment]
이 순위의 기초가 뭐예요?

**Comment by BurgessYT** [comment]
¿Cuál es la base para este ranking de visitas?

**Comment by no-Dark** [comment]
SimilarWeb

**Comment by hmg520cc** [comment]
https://www.hmg520.cc 红玫瑰社区 
视频站
https://www.tyjr.info 童颜巨乳  
https://www.zguifldh.com 醉鬼福利
http://www.fltv.buzz/  福利TV
https://www.mhnvl.com 梦幻女郎   
https://www.hmglt.pw 黑玫瑰影院
https://www.qpltv.com
